<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.mm-cinema</groupId>
    <artifactId>mm-cinema</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>yas</name>

    <modules>
        <module>auth</module>
        <module>blog</module>
        <module>booking</module>
        <module>campaign</module>
        <module>cinema</module>
        <module>common-library</module>
        <module>search</module>
        <module>customer</module>
        <module>employee</module>
        <module>payment</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <yas.version>1.0-SNAPSHOT</yas.version>
        <revision>1.0-SNAPSHOT</revision>

        <springdoc-openapi-starter-webmvc-ui.version>2.0.2</springdoc-openapi-starter-webmvc-ui.version>
        <org.mapstruct.version>	1.6.2</org.mapstruct.version>
        <org.lombok.version>1.18.34</org.lombok.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <logstash-logback-encoder.version>8.0</logstash-logback-encoder.version>
        <opentelemetry-logback.vesion>2.9.0-alpha</opentelemetry-logback.vesion>
        <spring-cloud.version>2023.0.3</spring-cloud.version>
        <springdoc-openapi-starter-webmvc-ui.version>2.6.0</springdoc-openapi-starter-webmvc-ui.version>
        <keycloak-spring-security-adapter.version>25.0.3</keycloak-spring-security-adapter.version>
        <org.keycloak.version>26.0.1</org.keycloak.version>
        <keycloak-spring-boot-starter.version>25.0.3</keycloak-spring-boot-starter.version>
        <commons-validator.version>1.9.0</commons-validator.version>
        <org.elasticsearch.version>8.15.3</org.elasticsearch.version>
        <testcontainers-keycloak.version>3.5.1</testcontainers-keycloak.version>
        <rest-assured.version>5.5.0</rest-assured.version>
        <instancio-junit.version>5.0.2</instancio-junit.version>
        <opencsv.version>5.9</opencsv.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.3.7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>